const refs = {
  maim: document.querySelector('main'),
  contentsList: document.querySelector('.gallery'),
  searchInput: document.querySelector('.search__input'),
  form: document.querySelector('.search'),
  errorText: document.querySelector('.search__text'),
  paginationList: document.querySelector('.pagination'),
  backdrop: document.querySelector('.backdrop'),
  modalWindow: document.querySelector('.modal'),
  btnModalClose: document.querySelector('.modal__close'),
  modalPopular: document.querySelector('.popularity'),
  modalTags: document.querySelector('.tags'),
  modalRaiting: document.querySelector('.vote_average'),
  modalTitle: document.querySelector('.original_title'),
  modalOverview: document.querySelector('.overview'),
  modalContainer: document.querySelector('.modal__container'),
  toggleThemeBtn: document.querySelector('.user-tools__btn--toggle'),
  scrollToTop: document.querySelector('.fix-wrapper'),
  btnListModal: document.querySelector('.modal__btn-list'),
  addWatch: document.querySelector('.modal__btn--to-watched'),
  addQueue: document.querySelector('.modal__btn--to-queue'),
  myLibrary: document.querySelector('.library'),
  watchedLibraryBrn: document.querySelector('.change-btn--watched'),
  queueLibraryBrn: document.querySelector('.change-btn-queue'),
  changeListLib: document.querySelector('.change-liset'),
  sortMenu: document.querySelector('.user-tools__btn--menu'),
  tagsMenu: document.querySelector('.menu-tags'),
  tagsList: document.querySelector('.menu-tags__list'),
  leftBoxModal: document.querySelector('.left-box'),
  rightBoxModal: document.querySelector('.rigth-box'),
};

export { refs };
